-- Explore All objects in the Database
SELECT * FROM INFORMATION_SCHEMA.TABLES;

-- Explore All Columns in the Database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_name = 'dim_customers'

-- PART I: Dimensions Exploration
-- E.g. All countries that customers come from
SELECT DISTINCT country FROM gold.dim_customers

--Explore all categories, sub category, product of the product
SELECT DISTINCT 
	category, 
	sub_category, 
	product_name FROM gold.dim_products
ORDER BY category,sub_category,product_name

-- Date Exploration
-- E.g Find the date of the first and last order
-- How many years of sales are availabe
SELECT 
	MIN (order_date) AS first_order_date,
	MAX (order_date) AS last_order_date,
	DATEDIFF(MONTH, MIN(order_date), MAX(order_date)) AS order_range_years
FROM gold.fact_sales

-- E.g Find the youngest and the older customer
SELECT
	MIN(birthday) AS olderest_birthday,
	DATEDIFF(year,MIN(birthday), GETDATE()) AS oldest_age,
	MAX(birthday) AS youngest_birthday,
	DATEDIFF(year,MAX(birthday), GETDATE()) AS youngest_age
FROM gold.dim_customers

-- PART II: Measures Exploration
/*	Find the total Sales
	Find how many items are sold
	Find the average selling price
	Find the total number of Orders
*/
SELECT 
	SUM(sales_amount) AS total_sales,
	SUM(quantity) AS total_sold_items,
	AVG(price) AS avg_price,
	COUNT(DISTINCT(order_number)) AS total_orders
FROM gold.fact_sales

--	Find the total number of customers
SELECT COUNT (customer_key) AS total_customer FROM gold.dim_customers

-- 	Find the total number of customers that has placed an order
SELECT COUNT(DISTINCT (customer_key)) AS total_customer_orders FROM gold.fact_sales

--	Find the total number of products
SELECT COUNT(product_key) AS total_products FROM gold.dim_products

-- Generate a Report that shows all key metrics of the business
SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL 
SELECT 'Total Sold Items' AS measure_name, SUM(quantity) AS measure_value FROM gold.fact_sales
UNION ALL 
SELECT 'Average Price' AS measure_name, AVG(price) AS measure_value FROM gold.fact_sales
UNION ALL 
SELECT 'Total Num Orders' AS measure_name, COUNT(DISTINCT(order_number)) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Num Customers' AS measure_name, COUNT (customer_key) AS measure_value FROM gold.dim_customers
UNION ALL
SELECT 'Total Num Products' AS measure_name, COUNT(product_key) AS measure_value FROM gold.dim_products

-- PART III: Magnitude Exploration - [Measure] BY [Dimension]
-- Find total customers by countries
SELECT 
	country,
	COUNT (customer_key) AS total_customer
FROM gold.dim_customers 
GROUP BY country
ORDER BY total_customer DESC

-- Find total customers by gender
SELECT 
	gender,
	COUNT (customer_key) AS total_customer	
FROM gold.dim_customers 
GROUP BY gender
ORDER BY total_customer DESC

-- Find total products by category
SELECT 
	COUNT (product_key) AS total_products, 
	category
FROM gold.dim_products 
GROUP BY category
ORDER BY total_products DESC

-- What is the average costs in each category?
SELECT 
	category,
	AVG (cost) AS average_cost
FROM gold.dim_products 
GROUP BY category
ORDER BY average_cost DESC

-- What is the total revenue generated for each category?
SELECT 
	dp.category AS category,
	SUM(fc.sales_amount) AS revenue
FROM gold.fact_sales fc LEFT JOIN gold.dim_products dp
ON dp.product_key = fc.product_key
GROUP BY dp.category
ORDER BY revenue DESC

-- Find total revenue is generated by each customer
SELECT 
	dc.customer_key AS customer_key,
	CONCAT(dc.first_name,' ', dc.last_name) AS customer_name,
	SUM(fc.sales_amount) AS revenue
FROM gold.fact_sales fc 
LEFT JOIN gold.dim_customers dc
ON dc.customer_key = fc.customer_key
GROUP BY dc.customer_key, dc.first_name, dc.last_name
ORDER BY revenue DESC

-- What is the distribution of sold items across countries?
SELECT 
	dc.country AS country,
	SUM(fs.quantity) AS number_sold_items,
	CAST(SUM(fs.quantity) * 100.0 / SUM(SUM(fs.quantity)) OVER() AS DECIMAL(10,2)) AS distribution_pct
FROM gold.fact_sales fs  
LEFT JOIN gold.dim_customers dc 
ON fs.customer_key = dc.customer_key
GROUP BY dc.country
ORDER BY distribution_pct DESC

-- PART IV: RANKING - Rank [Dimension] BY [Measure]
-- Which 5 products generate the highest revenue?
SELECT TOP 5
	fs.product_key AS product_key,
	dp.product_name AS product_name,
	SUM (fs.sales_amount) AS revenue
FROM gold.fact_sales fs 
LEFT JOIN gold.dim_products dp 
ON fs.product_key = dp.product_key
GROUP BY fs.product_key, dp.product_name
ORDER BY revenue DESC

-- Using window function
SELECT * FROM (
SELECT
	fs.product_key AS product_key,
	dp.product_name AS product_name,
	SUM (fs.sales_amount) AS revenue,
	ROW_NUMBER() OVER(ORDER BY SUM (fs.sales_amount) DESC) AS ranking_sales
FROM gold.fact_sales fs 
LEFT JOIN gold.dim_products dp 
ON fs.product_key = dp.product_key
GROUP BY fs.product_key, dp.product_name ) t
WHERE ranking_sales <= 5

-- What are the 5 worst-performing products in terms of sales?
SELECT TOP 5
	fs.product_key AS product_key,
	dp.product_name AS product_name,
	SUM (fs.sales_amount) AS revenue
FROM gold.fact_sales fs 
LEFT JOIN gold.dim_products dp 
ON fs.product_key = dp.product_key
GROUP BY fs.product_key, dp.product_name
ORDER BY revenue

-- Using window function
SELECT * FROM (
SELECT 
	fs.product_key AS product_key,
	dp.product_name AS product_name,
	SUM (fs.sales_amount) AS revenue, 
	ROW_NUMBER () OVER (ORDER BY SUM(fs.sales_amount)) AS ranking_low_sales
FROM gold.fact_sales fs 
LEFT JOIN gold.dim_products dp 
ON fs.product_key = dp.product_key
GROUP BY fs.product_key, dp.product_name) t
WHERE ranking_low_sales <= 5

-- Find the top 10 customers who have generated the highest revenue
SELECT TOP 10
	fs.customer_key,
	CONCAT (dc.first_name, ' ', dc.last_name) AS name,
	SUM(fs.sales_amount) AS revenue
FROM gold.fact_sales fs LEFT JOIN gold.dim_customers dc
ON fs.customer_key = dc.customer_key
GROUP BY fs.customer_key, dc.first_name, dc.last_name
ORDER BY revenue DESC

-- The 3 customers with the fewest orders placed
SELECT * FROM (
    SELECT 
        fs.customer_key AS customer_key,
        CONCAT(dc.first_name, ' ', dc.last_name) AS name,
        COUNT(DISTINCT fs.order_number) AS number_placed_orders,
        DENSE_RANK() OVER (ORDER BY COUNT(DISTINCT fs.order_number)ASC) AS ranking_fewest_orders
    FROM gold.fact_sales fs
    LEFT JOIN gold.dim_customers dc
    ON fs.customer_key = dc.customer_key
    GROUP BY 
        fs.customer_key, 
        dc.first_name, 
        dc.last_name) t
WHERE ranking_fewest_orders <= 3
ORDER BY ranking_fewest_orders, customer_key, name;

-- Advance Analytics

-- 1. Change Over Time Trend -- [Measure] By [Date Dimension]
-- Analyze Sales Performance Over Time
SELECT 
	YEAR(order_date) AS order_year,
	MONTH(order_date) AS order_month,
	SUM(sales_amount) AS total_sales,
	COUNT(DISTINCT(customer_key)) AS tota_customers,
	SUM(quantity) AS total_quantity
FROM gold.fact_sales
GROUP BY YEAR (order_date), MONTH(order_date)
ORDER BY order_year, order_month 

-- OR Using DATETRUNC
SELECT 
	DATETRUNC(MONTH, order_date) AS order_date,
	SUM(sales_amount) AS total_sales,
	COUNT(DISTINCT(customer_key)) AS tota_customers,
	SUM(quantity) AS total_quantity
FROM gold.fact_sales
GROUP BY DATETRUNC(MONTH, order_date)
ORDER BY order_date

-- 2. Cumulative Analysis 
-- Aggregate the data progressively over time
-- [Cumulative Measure] By [Date Dimension]
-- e.g. Running Total Sales By Year
-- Moving Average of Sales By Month

-- Calculate the total sales per month
--and the running total of sales over time
SELECT 
	*,
	SUM (total_sales) OVER(PARTITION BY DATETRUNC(YEAR, order_date) ORDER BY order_date) AS running_total_sales
	FROM (
		SELECT 
			DATETRUNC(MONTH, order_date) AS order_date,
			SUM (sales_amount) AS total_sales
		FROM gold.fact_sales
		WHERE order_date IS NOT NULL
		GROUP BY DATETRUNC(MONTH, order_date)) t 


-- 3 months moving average of the sales
SELECT 
	*,
	avg (avg_sales_current_month) OVER(ORDER BY order_date ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS '3_months_moving_sales'
	FROM (
		SELECT 
			DATETRUNC(MONTH, order_date) AS order_date,
			AVG (sales_amount) AS avg_sales_current_month
		FROM gold.fact_sales
		WHERE order_date IS NOT NULL
		GROUP BY DATETRUNC(MONTH, order_date)) t 

-- Yearly moving average
SELECT 
	*,
	avg (avg_sales_current_month) OVER(ORDER BY order_date) AS yearly_moving_avg
	FROM (
		SELECT 
			DATETRUNC(YEAR, order_date) AS order_date,
			AVG (sales_amount) AS avg_sales_current_month
		FROM gold.fact_sales
		WHERE order_date IS NOT NULL
		GROUP BY DATETRUNC(YEAR, order_date)) t 

-- 3. Performance Analysis 
-- Current[Measure] - Target[Sales] 

/* Analyze the yearly performance of products
by comparing each product's sales to both
its average sales performance and the previous year's sales.*/

WITH yearly_product_sales AS (
SELECT
	fc.product_key,
	YEAR(fc.order_date) AS order_year,
	dp.product_name,
	SUM(fc.sales_amount) AS current_sales
FROM gold.fact_sales fc LEFT JOIN gold.dim_products dp
ON fc.product_key =  dp.product_key
WHERE fc.order_date IS NOT NULL
GROUP BY fc.product_key,dp.product_name,YEAR (fc.order_date))
SELECT 
	*,
	AVG (current_sales) OVER (PARTITION BY product_name) AS avg_sales,
	current_sales - AVG (current_sales) OVER (PARTITION BY product_name) AS diff_avg,
	CASE WHEN current_sales - AVG (current_sales) OVER (PARTITION BY product_name)  > 0 THEN 'Above Average'
		 WHEN current_sales - AVG (current_sales) OVER (PARTITION BY product_name)  < 0 THEN 'Below Average'
			  ELSE 'Average'
		END avg_change, 
	-- Year-over-year Analysis
	LAG(current_sales, 1, NULL) OVER (PARTITION BY product_name ORDER BY order_year) AS previous_year_sales,
	current_sales - LAG(current_sales, 1, NULL) OVER (PARTITION BY product_name ORDER BY order_year) AS diff_yearly_sales, 
	CASE WHEN current_sales - LAG(current_sales, 1, NULL) OVER (PARTITION BY product_name ORDER BY order_year)  > 0 THEN 'Increase'
		 WHEN current_sales - LAG(current_sales, 1, NULL) OVER (PARTITION BY product_name ORDER BY order_year)  < 0 THEN 'Decrease'
			  ELSE 'Same'
		END previous_yaer_change
FROM yearly_product_sales
ORDER BY product_name, order_year

-- 4. Part-to-Whole Analysis (Proportional)
-- ([Measure]/Total[Measure]) * 100 By [Dimension]
-- E.g. (Sales / Total Sales) * 100 By Country

-- Which categories contribte the most to overall sales
WITH category_sales AS(
SELECT 
	dp.category,
	SUM (fs.sales_amount) AS cat_sales
FROM gold.fact_sales fs LEFT JOIN gold.dim_products dp
ON fs.product_key = dp.product_key
GROUP BY dp.category
)
SELECT 
	category, 
	cat_sales,
	SUM (cat_sales) OVER () AS total_sales,
	CAST(cat_sales * 100.0 / (SUM (cat_sales) OVER()) AS decimal(5,2)) AS percentage_of_total
FROM category_sales
ORDER BY percentage_of_total DESC

-- Data Segmentation (Group the data based on a specific range
-- [Measure] By [Measure]
-- e.g. Total Products By Sales Range, Total Customers By Age Range

/*Segment products into cost ranges and
count how many products fall into each segment*/
WITH product_segments AS(
SELECT 
	product_key,
	product_name,
	cost, 
	CASE WHEN cost < 100 THEN 'Below 100'
		WHEN cost BETWEEN 100 AND 500 THEN '100-500'
		WHEN cost BETWEEN 500 AND 1000 THEN '500-1000'
		ELSE 'Above 1000'
	END cost_range
FROM gold.dim_products
)
SELECT 
	cost_range,
	COUNT(product_key) AS total_products
FROM product_segments
GROUP BY cost_range
ORDER BY total_products DESC

/*Group customers into three segments based on their spending behavior:
- VIP: Customers with at least 12 months of history and spending more than €5,000.
- Regular: Customers with at least 12 months of history but spending €5,000 or less
- New: Customers with a lifespan less than 12 months.
And find the total number of customers by each group*/

WITH customer_spending AS (
    SELECT
        customer_key, 
        SUM(sales_amount) AS total_spending,
        DATEDIFF(MONTH, MIN(order_date), MAX(order_date)) AS lifespan
    FROM gold.fact_sales
    GROUP BY customer_key
),
customer_segments AS (
    SELECT
        customer_key,
        CASE 
            WHEN lifespan < 12 THEN 'New'
            WHEN total_spending > 5000 THEN 'VIP'
            ELSE 'Regular'
        END AS customer_category
    FROM customer_spending
)
SELECT
    customer_category,
    COUNT(customer_key) AS number_customer
FROM customer_segments
GROUP BY customer_category
ORDER BY number_customer DESC;

/*
==============================================================================
Customer Report
==============================================================================
Purpose:
	- This report consolidates key customer metrics and behaviors

Highlights:
	1. Gathers essential fields such as names, ages, and transaction details.
	2. Segments customers into categories (VIP, Regular, New) and age groups.
	3. Aggregates customer-level metrics:
		- total orders
		- total sales
		- total quantity purchased
		- total products
		- lifespan (in months)
	4. Calculates valuable KPIs:
		- recency (months since last order)
		- average order value
		- average monthly spend
==============================================================================
*/

-- =============================================================================
-- Create Report: gold.report_customers
-- =============================================================================
IF OBJECT_ID('gold.report_customers', 'V') IS NOT NULL
    DROP VIEW gold.report_customers;
GO

CREATE VIEW gold.report_customers AS 
WITH basic_info AS (
/*---------------------------------------------------------------------------
1) Base Query: Retrieves core columns from tables
---------------------------------------------------------------------------*/
SELECT 
	fs.order_number,
	fs.product_key,
	fs.order_date,
	fs.sales_amount,
	fs.quantity,
	dc.customer_key,
	CONCAT (dc.first_name, ' ', dc.last_name) AS name,
	dc.country,
	DATEDIFF(YEAR, dc.birthday, GETDATE()) AS age,
	dc.gender
FROM gold.fact_sales fs LEFT JOIN gold.dim_customers dc
ON fs.customer_key = dc.customer_key
WHERE order_date IS NOT NULL
) , customer_aggregation AS (
/*---------------------------------------------------------------------------
2) Customer Aggregations: Summarizes key metrics at the customer level
---------------------------------------------------------------------------*/
SELECT 
	customer_key,
	name,
	age,
	gender,
	SUM(sales_amount) AS total_sales,
	COUNT(DISTINCT order_number) AS total_orders,
	SUM(quantity) AS total_quantity,
	COUNT(DISTINCT product_key) AS total_products,
	MAX(order_date) AS last_order_date,
	DATEDIFF(MONTH,MIN (order_date),MAX(order_date)) AS lifespan
FROM basic_info
GROUP BY 
	customer_key,
	name,
	age,
	gender)
SELECT 
	customer_key,
	name, 
	gender,
	age, 
	CASE 
	 WHEN age >= 50 THEN '50 and Above'
	 WHEN age >= 40 THEN '40-49'
	 WHEN age >= 30 THEN '30-39'
	 WHEN age >= 20 THEN '20-29'
	 ELSE 'Below 20'
	END AS age_group,
	CASE WHEN lifespan < 12 THEN 'New'
         WHEN total_sales > 5000 THEN 'VIP'
         ELSE 'Regular'
	END AS customer_segments,
	total_sales,
	total_orders,
	total_quantity,
	total_products,
	lifespan,
	DATEDIFF(MONTH, last_order_date, GETDATE()) AS recency,
	--average order value
	total_sales / total_orders AS avg_order_value,
	--average monthly spend
	CASE WHEN lifespan = 0 THEN total_sales 
		 ELSE total_sales / lifespan 
	END AS avg_monthly_spend
FROM customer_aggregation

/*
===============================================================================
Product Report
===============================================================================
Purpose:
    - This report consolidates key product metrics and behaviors.

Highlights:
    1. Gathers essential fields such as product name, category, subcategory, and cost.
    2. Segments products by revenue to identify High-Performers, Mid-Range, or Low-Performers.
    3. Aggregates product-level metrics:
       - total orders
       - total sales
       - total quantity sold
       - total customers (unique)
       - lifespan (in months)
    4. Calculates valuable KPIs:
       - recency (months since last sale)
       - average order revenue (AOR)
       - average monthly revenue
===============================================================================
*/
-- =============================================================================
-- Create Report: gold.report_products
-- =============================================================================
IF OBJECT_ID('gold.report_products', 'V') IS NOT NULL
    DROP VIEW gold.report_products;
GO

CREATE VIEW gold.report_products AS 
WITH basic_info AS (
SELECT 
	fs.order_number,
	fs.customer_key,
	dp.product_key,
	dp.product_id,
	dp.product_name,
	dp.category,
	dp.sub_category,
	dp.cost,
	fs.sales_amount, 
	fs.quantity,
	fs.order_date
FROM gold.fact_sales fs LEFT JOIN gold.dim_products dp
ON fs.product_key = dp.product_key 
WHERE order_date IS NOT NULL
)
, product_aggregation AS (SELECT 
	product_key,
	product_id,
	product_name,
	category,
	sub_category,
	cost,
	COUNT(DISTINCT(order_number)) AS total_orders,
	SUM(sales_amount) AS total_sales, 
	SUM(quantity) AS total_quantity,
	MAX(order_date) AS last_order_date,
	COUNT(DISTINCT(customer_key)) AS num_unique_cust,
	DATEDIFF(MONTH, MIN(order_date), MAX(order_date)) AS lifespan
FROM basic_info
GROUP BY product_key,
		product_id,
		product_name,
		category,
		sub_category,
		cost )
SELECT 	product_key,
	product_id,
	product_name,
	category,
	sub_category,
	cost,
	total_orders,
	total_sales,
	CASE WHEN total_sales > 50000 THEN 'High-Performers'
		 WHEN total_sales >= 10000 THEN 'Mid-Performers'
		 ELSE 'Low-Performers'
	END AS performance_segments,
	total_quantity,
	last_order_date,
	num_unique_cust,
	lifespan, 
	-- recency (months since last sale)
	DATEDIFF (MONTH, last_order_date, GETDATE()) AS recency,
    -- average order revenue (AOR)
	total_sales / NULLIF(total_orders,0) AS avg_order_revenue,
    -- average monthly revenue
	CASE WHEN lifespan = 0 THEN total_sales
		 ELSE total_sales / lifespan
	END AS avg_monthly_revenue
	FROM product_aggregation 
GO

SELECT * FROM gold.report_products
