/*===========================================================================
Top Customers Analysis
===========================================================================

Purpose:
    Identify customers who generate the highest revenue.

Business Questions:
    1. Which customers generate the most revenue?

===========================================================================*/

-- Find total revenue is generated by each customer
SELECT 
	dc.customer_key AS customer_key,
	CONCAT(dc.first_name,' ', dc.last_name) AS customer_name,
	SUM(fc.sales_amount) AS revenue
FROM gold.fact_sales fc 
LEFT JOIN gold.dim_customers dc
ON dc.customer_key = fc.customer_key
GROUP BY dc.customer_key, dc.first_name, dc.last_name
ORDER BY revenue DESC
